language: go

go:
  - 1.11
install:
  - go get github.com/stretchr/testify/assert
before_script:
  - go build
script:
  - go test -v ./...
  - ./ra-chess-engine -perftjson perft-starting-position.json
  - ./ra-chess-engine -perftjson perft-test-positions.json
after_success:
  - ./ra-chess-engine --tactics --epd test-suites/basic.epd --tacticsthinkingtime 5000 || true
