language: go

go:
  - 1.11
install:
  - go get github.com/stretchr/testify/assert
after_success:
  - go build
  - ./ra-chess-engine -perftjson perft-test-positions.json
  - ./ra-chess-engine -perftjson perft-starting-position.json
